name: pdf
author: David PHAM-VAN <dev.nfet.net@gmail.com>
description: A pdf producer for Dart
homepage: https://github.com/davbfr/dart_pdf
version: 1.0.2

environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  meta: "^1.1.5"
  ttf_parser: "^1.0.0"
  vector_math: "^2.0.0"

dev_dependencies:
  test: any
